### ISSUE TITLE
Pb version

### ISSUE THREAD

**Issue by natxopedreira** [maxbbraun/thermal-face#4]
Hello!!

Would like to play with this, and im wondering if is possible to provide a pb version of the model?

I read that is planned to add landmarks? that would be very cool, do you think is possible?

Regards

**Comment by natxopedreira** [comment]
Im trying to reproduce your steps but im not able to download flir database, first tar file seems corrupted and i allways get an error` tar: Unexpected EOF in archive` tried to download several times.... did you have same problem?

**Comment by maxbbraun** [comment]
I'm focused on TF Lite for now. Note that all this is still a work in progress.

Adding landmarks is definitely possible, but would require a different approach and a different dataset.

I'm not sure how to fix the tar issue, unfortunately.

**Comment by natxopedreira** [comment]
Thank you, im now training the model on cloud auto ML, do you remember how many hours it takes? 

Also im new to CAML but i notice that you can export directly for edgetpu, is there any reason why you did not export that way and convert the model yourself?

I will try later to retrain a face model with only the tufts and ada data
