### ISSUE TITLE
tensorflowjs model 

### ISSUE THREAD

**Issue by kosullivansita** [maxbbraun/thermal-face#5]
I'd like to use this model with [Tensorflow.js](https://www.tensorflow.org/js/). The tflite model is not compatible with tensorflowjs. Could you export a tensorflowjs model?  

(yes, I know there is lots of info on training the model, but if you still have it setup in Cloud ML, I thought a polite ask to click the export button might save me the effort of setting up my own Cloud ML instance)

https://medium.com/tensorflow/build-and-deploy-tensorflow-js-models-with-the-power-of-automl-1985b8985083 

![image](https://user-images.githubusercontent.com/7659831/84776425-32e6ba80-afd8-11ea-9ad3-5e94111c4e1b.png)

**Comment by maxbbraun** [comment]
Here you go: [thermal_face_tf_js.zip](https://github.com/maxbbraun/thermal-face/files/4810094/thermal_face_tf_js.zip)
